name: Points
main: com.pvminecraft.points.Points
version: 1.5.1

commands:
    home:
        description: Go to your home point
        usage: /home
    sethome:
        description: Sets your home point to your current location
        usage: /sethome
    spawn:
        description: Teleports you to the spawn point
        usage: /spawn
    warp:
        description: Allows warp functionality
        usage: /warp [operation] [target]
    points:
        description: Allows the querying of plugin information
        usage: /points [operation]

permissions:
    points.*:
        description: Gives access to all Points functions
        children:
                points.spawn: true
                points.home: true
                points.warp: true
                points.admin: true
        points.spawn:
            description: Grants the ability to teleport to spawn
            default: true
        points.home:
            description: Gives the ability to set and use your home point
            default: true
        points.warp:
            description: Gives the ability to use warps
            default: true
        points.admin:
            description: Gives the ability to query Points information
            default: op
