debugging: false
checkupdates: true
features:
    warps:
        enabled: true
        social: true
        globals: true
        compass: true
        invites: true
    spawn:
        enabled: true
        bed: true
    home:
        enabled: true